---
- hosts: localhost
  name: Create AWS infrastructure with Terraforms
  vars:
    - deployment_id: 'DEFAULT_DEPLOYMENT'
    - deployment_directory: "../instances/TERRAFORM_{{ deployment_id }}"
  tasks:

    - name: Destroy Terraform deployment
      terraform:
        project_path: "./{{ deployment_directory }}/"
        state: absent

    - name: Destroy the instance Terraform directory
      file:
        path: "{{ deployment_directory }}"
        state: absent